import { IsUUID } from 'class-validator'
import { ApiProperty } from '@nestjs/swagger'

export class ExchangeMagicLinkDto {
  @ApiProperty({ description: 'The sessionId generated by the client when requesting the magic link' })
  @IsUUID()
  sessionId: string
}
